# Generated by Django 4.2.7 on 2025-12-26 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('categorie', models.CharField(choices=[('programmation', 'Programmation'), ('reseaux', 'Réseaux'), ('securite', 'Sécurité'), ('cloud', 'Cloud Computing'), ('data', 'Data Science'), ('autre', 'Autre')], default='programmation', max_length=50)),
                ('niveau', models.CharField(choices=[('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('avance', 'Avancé')], default='debutant', max_length=20)),
                ('description', models.TextField()),
                ('objectifs', models.TextField()),
                ('programme', models.TextField()),
                ('duree', models.CharField(help_text='Durée de la formation (ex: 3 jours, 24h)', max_length=100)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disponible', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='formations/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations',
                'ordering': ['categorie', 'titre'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('categorie', models.CharField(choices=[('developpement', 'Développement'), ('infrastructure', 'Infrastructure IT'), ('securite', 'Sécurité'), ('consulting', 'Consulting'), ('support', 'Support Technique')], default='developpement', max_length=50)),
                ('description', models.TextField()),
                ('description_courte', models.CharField(max_length=200)),
                ('icone', models.CharField(help_text='Classe Font Awesome (ex: fa-code)', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('ordre', models.IntegerField(default=0, help_text="Ordre d'affichage")),
                ('est_actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['ordre', 'titre'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('sujet', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('traite', models.BooleanField(default=False)),
                ('formation_interessee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.formation')),
                ('service_interesse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.service')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['-date_creation'],
            },
        ),
    ]
