# Generated by Django 4.2.7 on 2025-12-26 22:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_titre', models.CharField(default='Transformez votre entreprise avec nos solutions IT', max_length=200)),
                ('hero_sous_titre', models.TextField(default='GLOBALT-IT vous accompagne dans votre transformation digitale', max_length=500)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='config/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('about_titre', models.CharField(default='Notre mission', max_length=200)),
                ('about_description', models.TextField(default='Chez GLOBALT-IT, nous croyons que la technologie est un levier puissant pour transformer les entreprises.', max_length=1000)),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='config/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('telephone', models.CharField(default='+33 1 23 45 67 89', max_length=20)),
                ('email', models.EmailField(default='contact@globalt-it.fr', max_length=254)),
                ('adresse', models.TextField(default="123 Rue de l'Innovation\n75000 Paris\nFrance")),
                ('facebook_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('meta_title', models.CharField(default='GLOBALT-IT - Services Informatiques & Formations', max_length=60)),
                ('meta_description', models.TextField(default='GLOBALT-IT : Services informatiques sur-mesure et formations professionnelles pour transformer votre entreprise.', max_length=160)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration du site',
                'verbose_name_plural': 'Configuration du site',
            },
        ),
    ]
