# Generated by Django 4.2.7 on 2025-12-26 23:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_siteconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='config/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'svg'])]),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='nom_site',
            field=models.CharField(default='GLOBALT-IT', max_length=100),
        ),
    ]
