# Generated by Django 4.2.7 on 2025-12-30 14:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_siteconfiguration_logo_siteconfiguration_nom_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text="Titre de l'image", max_length=100)),
                ('description', models.CharField(blank=True, help_text='Description optionnelle', max_length=200)),
                ('image', models.ImageField(upload_to='carousel/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('ordre', models.IntegerField(default=0, help_text="Ordre d'affichage dans le carousel")),
                ('est_actif', models.BooleanField(default=True, help_text='Afficher cette image dans le carousel')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Image Carousel',
                'verbose_name_plural': 'Images Carousel',
                'ordering': ['ordre', 'titre'],
            },
        ),
    ]
