# Generated by Django 4.2.7 on 2025-12-31 10:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_carouselimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text="Titre de l'image", max_length=100)),
                ('description', models.CharField(blank=True, help_text='Description optionnelle', max_length=200)),
                ('image', models.ImageField(upload_to='about/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('ordre', models.IntegerField(default=0, help_text="Ordre d'affichage dans la section about")),
                ('est_actif', models.BooleanField(default=True, help_text='Afficher cette image dans la section about')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Image About',
                'verbose_name_plural': 'Images About',
                'ordering': ['ordre', 'titre'],
            },
        ),
    ]
