# Generated by Django 4.2.7 on 2026-01-02 09:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_aboutimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom du client', max_length=100)),
                ('entreprise', models.CharField(blank=True, help_text='Entreprise du client (optionnel)', max_length=100)),
                ('poste', models.CharField(blank=True, help_text='Poste/fonction du client (optionnel)', max_length=100)),
                ('commentaire', models.TextField(help_text="Commentaire de l'avis")),
                ('note', models.IntegerField(choices=[(1, '1 étoile'), (2, '2 étoiles'), (3, '3 étoiles'), (4, '4 étoiles'), (5, '5 étoiles')], default=5, help_text='Note sur 5 étoiles')),
                ('photo', models.ImageField(blank=True, help_text='Photo du client (optionnel)', null=True, upload_to='reviews/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('est_actif', models.BooleanField(default=True, help_text='Afficher cet avis sur le site')),
                ('ordre', models.IntegerField(default=0, help_text="Ordre d'affichage des avis")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Avis client',
                'verbose_name_plural': 'Avis clients',
                'ordering': ['ordre', '-date_creation'],
            },
        ),
    ]
