# Generated by Django 4.2.7 on 2026-01-03 08:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_customerreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom du partenaire', max_length=100)),
                ('site_web', models.URLField(help_text='URL du site web du partenaire')),
                ('logo', models.ImageField(help_text='Logo du partenaire', upload_to='partners/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'svg'])])),
                ('description', models.TextField(blank=True, help_text='Description optionnelle du partenaire')),
                ('ordre', models.IntegerField(default=0, help_text="Ordre d'affichage")),
                ('est_actif', models.BooleanField(default=True, help_text='Afficher ce partenaire sur le site')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Partenaire',
                'verbose_name_plural': 'Partenaires',
                'ordering': ['ordre', 'nom'],
            },
        ),
    ]
