# Generated by Django 4.2.7 on 2026-01-27 13:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text='Titre du poste', max_length=200)),
                ('description', models.TextField(help_text='Description détaillée du poste')),
                ('missions', models.TextField(help_text='Principales missions du poste')),
                ('profil_recherche', models.TextField(help_text='Profil et compétences recherchées')),
                ('avantages', models.TextField(blank=True, help_text='Avantages proposés')),
                ('type_contrat', models.CharField(choices=[('CDI', 'CDI'), ('CDD', 'CDD'), ('STAGE', 'Stage'), ('ALTERNANCE', 'Alternance'), ('FREELANCE', 'Freelance'), ('INTERIM', 'Intérim')], default='CDI', max_length=20)),
                ('lieu', models.CharField(help_text='Lieu de travail', max_length=100)),
                ('salaire_min', models.DecimalField(blank=True, decimal_places=2, help_text='Salaire minimum', max_digits=10, null=True)),
                ('salaire_max', models.DecimalField(blank=True, decimal_places=2, help_text='Salaire maximum', max_digits=10, null=True)),
                ('experience_min', models.CharField(blank=True, help_text='Expérience minimum requise', max_length=50)),
                ('date_debut', models.DateField(blank=True, help_text='Date de début souhaitée', null=True)),
                ('date_limite', models.DateField(blank=True, help_text='Date limite de candidature', null=True)),
                ('est_actif', models.BooleanField(default=True, help_text='Publier cette offre')),
                ('urgent', models.BooleanField(default=False, help_text='Marquer cette offre comme urgente')),
                ('ordre', models.IntegerField(default=0, help_text="Ordre d'affichage")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Offre d'emploi",
                'verbose_name_plural': "Offres d'emploi",
                'ordering': ['-urgent', '-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('adresse', models.TextField(blank=True)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('experience', models.TextField(help_text='Expérience professionnelle')),
                ('formations', models.TextField(blank=True, help_text='Formations et diplômes')),
                ('competences', models.TextField(blank=True, help_text='Compétences techniques')),
                ('motivations', models.TextField(help_text='Lettre de motivation')),
                ('salaire_attendu', models.CharField(blank=True, help_text='Prétentions salariales', max_length=50)),
                ('disponibilite', models.CharField(blank=True, help_text='Disponibilité', max_length=100)),
                ('cv', models.FileField(help_text='Formats acceptés : PDF, DOC, DOCX', upload_to='candidatures/cv/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx'])])),
                ('lettre_motivation', models.FileField(blank=True, help_text='Lettre de motivation (optionnelle)', null=True, upload_to='candidatures/lm/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx'])])),
                ('statut', models.CharField(choices=[('NOUVELLE', 'Nouvelle'), ('EN_COURS', 'En cours de traitement'), ('ENTRETIEN', 'Entretien programmé'), ('ACCEPTEE', 'Acceptée'), ('REFUSEE', 'Refusée'), ('ARCHIVEE', 'Archivée')], default='NOUVELLE', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Notes internes')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('job_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='main.joboffer')),
            ],
            options={
                'verbose_name': 'Candidature',
                'verbose_name_plural': 'Candidatures',
                'ordering': ['-date_creation'],
            },
        ),
    ]
