# Generated by Django 4.2.7 on 2026-02-01 14:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_joboffer_jobapplication'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpontaneousApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('poste_souhaite', models.CharField(help_text='Type de poste ou domaine recherché', max_length=200)),
                ('motivations', models.TextField(help_text='Lettre de motivation')),
                ('experience', models.TextField(blank=True, help_text='Expérience professionnelle')),
                ('formations', models.TextField(blank=True, help_text='Formations et diplômes')),
                ('competences', models.TextField(blank=True, help_text='Compétences techniques')),
                ('salaire_attendu', models.CharField(blank=True, help_text='Prétentions salariales', max_length=50)),
                ('disponibilite', models.CharField(blank=True, help_text='Disponibilité', max_length=100)),
                ('cv', models.FileField(help_text='Formats acceptés : PDF, DOC, DOCX', upload_to='candidatures/cv/spontanees/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx'])])),
                ('lettre_motivation', models.FileField(blank=True, help_text='Lettre de motivation (optionnelle)', null=True, upload_to='candidatures/lm/spontanees/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx'])])),
                ('statut', models.CharField(choices=[('NOUVELLE', 'Nouvelle'), ('EN_COURS', 'En cours de traitement'), ('ENTRETIEN', 'Entretien programmé'), ('ACCEPTEE', 'Acceptée'), ('REFUSEE', 'Refusée'), ('ARCHIVEE', 'Archivée')], default='NOUVELLE', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Notes internes')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Candidature spontanée',
                'verbose_name_plural': 'Candidatures spontanées',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.AddField(
            model_name='joboffer',
            name='image',
            field=models.ImageField(blank=True, help_text="Image de présentation de l'offre", null=True, upload_to='job_offers/'),
        ),
    ]
