# Generated by Django 4.2.7 on 2026-02-02 11:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_spontaneousapplication_joboffer_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('poste_souhaite', models.CharField(max_length=200, verbose_name='Poste souhaité')),
                ('message', models.TextField(verbose_name='Message de motivation')),
                ('cv', models.FileField(upload_to='candidatures/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='CV (PDF uniquement)')),
                ('statut', models.CharField(choices=[('nouvelle', 'Nouvelle'), ('en_cours', 'En cours'), ('traitee', 'Traitée'), ('archivee', 'Archivée')], default='nouvelle', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Candidature active')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Candidature',
                'verbose_name_plural': 'Candidatures',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='job_offer',
        ),
        migrations.DeleteModel(
            name='SpontaneousApplication',
        ),
        migrations.DeleteModel(
            name='JobApplication',
        ),
        migrations.DeleteModel(
            name='JobOffer',
        ),
    ]
