# Generated by Django 4.2.7 on 2026-02-17 16:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_recruitment_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom de la marque', max_length=100)),
                ('site_web', models.URLField(help_text='URL du site web de la marque')),
                ('logo', models.ImageField(help_text='Logo de la marque', upload_to='brands/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp', 'svg'])])),
                ('description', models.TextField(blank=True, help_text='Description optionnelle de la marque')),
                ('ordre', models.IntegerField(default=0, help_text="Ordre d'affichage")),
                ('est_actif', models.BooleanField(default=True, help_text='Afficher cette marque sur le site')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Marque',
                'verbose_name_plural': 'Marques',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='nom_site',
            field=models.CharField(default='Global-IT', max_length=100),
        ),
    ]
