# Generated by Django 4.2.7 on 2026-02-18 12:14

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_brand_alter_siteconfiguration_nom_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(help_text="Titre de l'actualité", max_length=200)),
                ('description', models.TextField(help_text="Description détaillée de l'actualité")),
                ('description_courte', models.CharField(help_text="Résumé court de l'actualité", max_length=200)),
                ('image', models.ImageField(blank=True, help_text="Image illustrant l'actualité", null=True, upload_to='news/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('date_publication', models.DateTimeField(default=django.utils.timezone.now, help_text='Date de publication')),
                ('ordre', models.IntegerField(default=0, help_text="Ordre d'affichage")),
                ('est_actif', models.BooleanField(default=True, help_text='Afficher cette actualité')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Actualité',
                'verbose_name_plural': 'Actualités',
                'ordering': ['-date_publication', 'ordre'],
            },
        ),
    ]
