# Generated by Django 4.2.7 on 2026-02-18 14:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom de la catégorie', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description de la catégorie')),
                ('image', models.ImageField(blank=True, help_text='Image représentant la catégorie', null=True, upload_to='categories/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('ordre', models.IntegerField(default=0, help_text="Ordre d'affichage")),
                ('est_actif', models.BooleanField(default=True, help_text='Afficher cette catégorie')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Image supplémentaire du produit', upload_to='products/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('alt_text', models.CharField(blank=True, help_text="Texte alternatif pour l'image", max_length=100)),
                ('ordre', models.IntegerField(default=0, help_text="Ordre d'affichage")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Image Produit',
                'verbose_name_plural': 'Images Produits',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(help_text='Nom du produit', max_length=200)),
                ('description', models.TextField(help_text='Description détaillée du produit')),
                ('description_courte', models.CharField(help_text='Résumé court du produit', max_length=200)),
                ('prix', models.DecimalField(decimal_places=2, help_text='Prix du produit', max_digits=10)),
                ('image_principale', models.ImageField(help_text='Image principale du produit', upload_to='products/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'webp'])])),
                ('stock', models.IntegerField(default=0, help_text='Quantité en stock')),
                ('reference', models.CharField(help_text='Référence unique du produit', max_length=50, unique=True)),
                ('est_en_promotion', models.BooleanField(default=False, help_text='Produit en promotion')),
                ('prix_promotionnel', models.DecimalField(blank=True, decimal_places=2, help_text='Prix promotionnel', max_digits=10, null=True)),
                ('est_actif', models.BooleanField(default=True, help_text='Afficher ce produit')),
                ('ordre', models.IntegerField(default=0, help_text="Ordre d'affichage")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.category')),
                ('images_supplementaires', models.ManyToManyField(blank=True, related_name='products', to='main.productimage')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['ordre', '-date_creation'],
            },
        ),
    ]
