# Generated by Django 4.2.7 on 2026-02-18 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_category_productimage_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reference',
            field=models.CharField(blank=True, help_text='Référence unique du produit (optionnelle)', max_length=50, null=True, unique=True),
        ),
    ]
